### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by melissamcewen** [fudge66/bapi-p6-expresso#1]
Hi I am reviewing for codecademy. Great job on this! It's a complicated project and yours works nicely. 

All the tests pass when I run `npm test` but I found one error I will file an issue for. 

Congrads on finishing the course! I hope you enjoyed it and learned a lot!

**Comment by fudge66** [comment]
Thanks Melissa :)

I did enjoy it, it's a wonderful course.
