### ISSUE TITLE
Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: MenuItem.name

### ISSUE THREAD

**Issue by melissamcewen** [fudge66/bapi-p6-expresso#2]
I kept getting this error when running tests. Turns out that the API was sending the 400, which meant it passed the test, but was still inserting the invalid menu item! A great example of why you can't completely trust tests. 

So after this if statement it should throw the 400 and stop...but it doesn't
https://github.com/fudge66/bapi-p6-expresso/blob/master/api/menu-items.js#L71-L73

It keeps going and adds the invalid item. Adding in an else here prevents this from happening

```javascript
menuItemsRouter.put('/:menuItemId', (req, res, next) => {
  const id = req.params.menuItemId,
  name = req.body.menuItem.name,
  description = req.body.menuItem.description,
  inventory = req.body.menuItem.inventory,
  price = req.body.menuItem.price;
  if (!name || !description || !inventory || !price) {
    res.sendStatus(400);
  } else {



    const sql = `UPDATE "MenuItem"
    SET "name" = $name, description = $description, 
    inventory = $inventory, price = $price
    WHERE "id" = $id;`,
    values = {
      $id: id,
      $name: name,
      $description: description,
      $inventory: inventory,
      $price: price,
    };

    db.run(sql, values, (err) => {
      if (err) {
        return next(err);
      }
      db.get(`SELECT * FROM "MenuItem" WHERE id = $id;`, {$id: id}, (err, menuItem) => {
        res.status(200).json({menuItem: menuItem});
      });
    }); }
  });
```

**Comment by fudge66** [comment]
Wow, that's interesting. Instead of adding `else {` could it also be fixed by adding `return;` after `res.sendStatus(400);`.

I'll keep these things in mind in the future, thanks Melissa.

**Comment by melissamcewen** [comment]
Yeah it could, you could also use some validator callback functions. I think though once you're using control flow like `if` it's good to just use control flow patterns `else if` `else` etc.

**Comment by fudge66** [comment]
Great, thanks for the advice.

**Comment by melissamcewen** [comment]
If you want to see some other solutions you can usually just search for parts of the starter code on Github too, I use that a lot just to see what other people are doing 😎

**Comment by fudge66** [comment]
Lol, cool tip :)
